apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-b-prod
  namespace: argocd
spec:
  project: marketing-prod
  source:
    repoURL: https://github.com/Ratomir/argocd.git
    targetRevision: HEAD
    path: argoapps/serviceB
    directory:
      recurse: true
  destination:
    name: argocd-prod
    server: ''
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false