apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-c-dev
  namespace: argocd
spec:
  project: marketing-dev
  source:
    repoURL: https://github.com/Ratomir/argocd.git
    targetRevision: HEAD
    path: argoapps/serviceC
    directory:
      recurse: true
  destination:
    name: argocd-dev
    server: ''
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false