apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketing-dev
  namespace: argocd
spec:
  project: marketing-dev
  source:
    repoURL: https://github.com/Ratomir/argocd.git
    targetRevision: HEAD
    path: argoinstall/dev
    directory:
      recurse: true
  destination:
    server: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketing-prod
  namespace: argocd
spec:
  project: marketing-prod
  source:
    repoURL: https://github.com/Ratomir/argocd.git
    targetRevision: HEAD
    path: argoinstall/prod
    directory:
      recurse: true
  destination:
    server: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false