apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serviceA
  namespace: argocd
spec:
  project: marketing-prod
  source:
    repoURL: https://github.com/ratomirvu/argocd.git
    targetRevision: HEAD
    path: argoapps/serviceA
    directory:
      recurse: true
  destination:
    server: argocd-prod
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false